title: Resume | Jeongjun Kim
description:  A beautiful template for your CV.
url: https://jeongjun-kim.github.io/jeongjunkim/
baseurl: ''
theme_skin: black

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
