title: Resume | Jeong Jun Kim
description:  
url: https://jeongjunkim.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
